### ISSUE TITLE
The new version of Proxmox, 7.4.3, has been released. Patch 7.3.3 is not compatible with this new version.

### ISSUE THREAD

**Issue by foura1512** [thundervm/proxmox-windows-template#1]

**Comment by Kevinvincentals** [comment]
+1 for this.

**Comment by AniTexs** [comment]
+1

**Comment by thundervm** [comment]
I provided a test patch to the OP but never heard back.

Is anyone able to give me access to a test server so i can attempt to create a fix?

**Comment by thundervm** [comment]
@AniTexs @Kevinvincentals and @foura1512

**Comment by Kevinvincentals** [comment]
We ended up using Qemu guest agent with Some funky powershell scripts to resize disk spaces etc.

If you still need a test server, let me know via email, kevin@tideo.dk

**Comment by thundervm** [comment]
patched
